### ISSUE TITLE
macOS 打包 Web 失败

### ISSUE THREAD

**Issue by chenfengyanyu** [tw93/Pake#159]
相关环境
os: macos Big Sur 11.4
pake: npm install -g pake-cli && pake --version 显示的版本是0.1.2
rustc：版本 rustc 1.64.0 (a55dd71d5 2022-09-19)

打包时：
pake http://jartto.wang --name JarttoBlog --transparent

报错 （部分）
```bash
You have not provided an app icon, use the default icon.(use --icon option to assign an icon)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/shelljs@^0.8.11.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jartto/.npm/_logs/2022-12-12T12_51_07_668Z-debug.log
file:///Users/jartto/.nvm/versions/node/v16.12.0/lib/node_modules/pake-cli/dist/cli.js:1793
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///Users/jartto/.nvm/versions/node/v16.12.0/lib/node_modules/pake-cli/dist/cli.js:1793:24
    at /Users/jartto/.nvm/versions/node/v16.12.0/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:404:5)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
```
辛苦帮忙看看，不胜感激~

**Comment by chenfengyanyu** [comment]
对 Node 版本有要求，升级为 V16.18.1，问题解决

**Comment by tw93** [comment]
谢谢反馈 我去更新一下文档说明
