### ISSUE TITLE
Ubuntu 打包错误，无法找到文件以及重复提示安装rust

### ISSUE THREAD

**Issue by zhucaidan** [tw93/Pake#160]
Ubuntu 版本为 Ubuntu 22.04.1 LTS，amd64

本机已安装最新rust和node，但是执行时依旧提示需要安装rust

接下来日志为：

`✔ Downloading Rust
✔ please input your application name … blog

up to date, audited 235 packages in 557ms

76 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> pake-cli@0.1.2 build
> npm run tauri build --release

> pake-cli@0.1.2 tauri
> tauri build

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, copyfile '/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/deb/blog_1.0.0_amd64.deb' -> '/home/ubuntu/blog.deb'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: "/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/deb/blog_1.0.0_amd64.deb",
  dest: "/home/ubuntu/blog.deb"
}

Node.js v18.12.1`

**Comment by neutrous** [comment]
显示的是**文件没有找到**，请查看`/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/deb/blog_1.0.0_amd64.deb`是否存在。

**Comment by zhucaidan** [comment]
> 显示的是**文件没有找到**，请查看`/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/deb/blog_1.0.0_amd64.deb`是否存在。

![image](https://user-images.githubusercontent.com/47970938/207104466-d8a5e7f2-713d-46d8-a5f8-103d846709bc.png)

target文件夹都没有。。编译也没提示错误啊

**Comment by zhucaidan** [comment]
> 

试过了。。还是一样的错误，应该不是图标问题，我手动指定了一个png文件

’‘’shell
sudo pake wordpress.com --transparent --icon '/home/ubuntu/1.png'
‘’‘

**Comment by midpoint** [comment]
同样的错误信息

**Comment by JabinSun** [comment]
同样遇到了这个问题

**Comment by JabinSun** [comment]
> 各位打包失败的，自检一下是否安装Ubuntu/Debian/Arch等系统所需要的依赖。目前脚本并没有内置自动识别你系统，自动帮你安装依赖的功能。
> 
> 打包的时候第一行就有提示的了。 $ sudo pake wordpress.com --transparent To build the Linux app, you need to install Rust and Linux package See more in **https://tauri.app/v1/guides/getting-started/prerequisites#installing** 我刚随便找了一个wsl2封装的ubuntu 20.04，打包没有任何问题。

按照提示装了依赖以后有新的报错：
Compiling app v0.1.0 (/usr/local/lib/node_modules/pake-cli/src-tauri)
    Finished release [optimized] target(s) in 14.69s
    Bundling weekly_1.0.0_amd64.deb (/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/deb/weekly_1.0.0_amd64.deb)
    Bundling weekly_1.0.0_amd64.AppImage (/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/appimage/weekly_1.0.0_amd64.AppImage)
       Error failed to bundle project: error running appimage.sh: error running appimage.sh: `failed to run /usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/appimage/build_appim
age.sh`
file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1793
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1793:24
    at /usr/local/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

Node.js v19.2.0

**Comment by zzy619** [comment]
> > error running appimage.sh: error running appimage.sh
> 
> 两个解决办法：
> 
> 1. 参考该链接修复：[[bug] tauri build fails with "error running appimage.sh" tauri-apps/tauri#3278](https://github.com/tauri-apps/tauri/issues/3278)
> 2. cd /usr/local/lib/node_modules/pake-cli/,找到src-tauri/tauri.linux.conf.json，删除里面的appimage字段，这样只打包deb就行了。修改后` "targets": ["deb"]`，然后重新运行打包。

macOS呢

**Comment by zhucaidan** [comment]
> > error running appimage.sh: error running appimage.sh
> 
> 两个解决办法：
> 
> 1. 参考该链接修复：[[bug] tauri build fails with "error running appimage.sh" tauri-apps/tauri#3278](https://github.com/tauri-apps/tauri/issues/3278)
> 2. cd /usr/local/lib/node_modules/pake-cli/,找到src-tauri/tauri.linux.conf.json，删除里面的appimage字段，这样只打包deb就行了。修改后` "targets": ["deb"]`，然后重新运行打包。

试过了，只保留了deb还是同样错误。。😂

**Comment by josangmi** [comment]
macos m1 类似的错误
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

**Comment by josangmi** [comment]
我这边解决了，单独安装rust即可。 mac m1
