### ISSUE TITLE
cannot pack

### ISSUE THREAD

**Issue by dddachui** [tw93/Pake#175]
Error failed to get project out directory: failed to get cargo metadata: Permission denied (os error 13)
file:///usr/local/node/lib/node_modules/pake-cli/dist/cli.js:1817
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///usr/local/node/lib/node_modules/pake-cli/dist/cli.js:1817:24
    at /usr/local/node/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:404:5)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

**Comment by tw93** [comment]
什么系统？
参考 https://github.com/tw93/Pake/issues/160

**Comment by tw93** [comment]
先关闭下，可以从之前历史issue中寻找解决办法
