### ISSUE TITLE
SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by jiyiren** [tw93/Pake#176]
```bash
/usr/local/lib/node_modules/pake-cli/cli.js:2
import './dist/cli.js';
       ^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

![image](https://user-images.githubusercontent.com/7271380/208038260-f31cc92c-d02a-4067-a9f9-9e29b4e4cb96.png)

操作系统
<img width="483" alt="image" src="https://user-images.githubusercontent.com/7271380/208038540-ecb28982-6f53-4bf3-b277-e79b3e5c1565.png">

Node/Npm 版本

```
$ node -v
v10.15.3
$ npm -v
6.9.0
```

**Comment by jiyiren** [comment]
能不能做一个服务，用户只需要填写网站，上传图标，提供 Linux Mac Windows 版本选择，然后用户点击一下就能生成打包好后的应用。

**Comment by tw93** [comment]
node 版本太低了，升级到16试试，然后
先卸载再重新安装
你说的网站有计划，计划中啦

**Comment by tw93** [comment]
先关闭，如有问题再打开，也欢迎直接去电报群交流
