### ISSUE TITLE
安裝之後無法執行

### ISSUE THREAD

**Issue by changchichung** [tw93/Pake#177]
安裝，看樣子應該是有安裝成功？
```
cch@c034:~/git/Pake$ npm install -g pake-cli
/home/cch/.nvm/versions/node/v10.19.0/bin/pake -> /home/cch/.nvm/versions/node/v10.19.0/lib/node_modules/pake-cli/cli.js
npm WARN notsup Unsupported engine for @tauri-apps/api@1.2.0: wanted: {"node":">= 14.6.0","npm":">= 6.6.0","yarn":">= 1.19.1"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: @tauri-apps/api@1.2.0
npm WARN notsup Unsupported engine for commander@9.4.1: wanted: {"node":"^12.20.0 || >=14"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: commander@9.4.1
npm WARN notsup Unsupported engine for update-notifier@6.0.2: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: update-notifier@6.0.2
npm WARN notsup Unsupported engine for chalk@5.2.0: wanted: {"node":"^12.17.0 || ^14.13 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: chalk@5.2.0
npm WARN notsup Unsupported engine for ora@6.1.2: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: ora@6.1.2
npm WARN notsup Unsupported engine for file-type@18.0.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: file-type@18.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-win32-x64-msvc@1.2.2 (node_modules/pake-cli/node_modules/@tauri-apps/cli/node_modules/@tauri-apps/cli-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-win32-x64-msvc@1.2.2: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-darwin-x64@1.2.2 (node_modules/pake-cli/node_modules/@tauri-apps/cli/node_modules/@tauri-apps/cli-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-darwin-x64@1.2.2: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-darwin-arm64@1.2.2 (node_modules/pake-cli/node_modules/@tauri-apps/cli/node_modules/@tauri-apps/cli-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-darwin-arm64@1.2.2: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-linux-arm64-musl@1.2.2 (node_modules/pake-cli/node_modules/@tauri-apps/cli/node_modules/@tauri-apps/cli-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-linux-arm64-musl@1.2.2: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-linux-arm64-gnu@1.2.2 (node_modules/pake-cli/node_modules/@tauri-apps/cli/node_modules/@tauri-apps/cli-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-linux-arm64-gnu@1.2.2: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-win32-ia32-msvc@1.2.2 (node_modules/pake-cli/node_modules/@tauri-apps/cli/node_modules/@tauri-apps/cli-win32-ia32-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-win32-ia32-msvc@1.2.2: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @tauri-apps/cli-linux-arm-gnueabihf@1.2.2 (node_modules/pake-cli/node_modules/@tauri-apps/cli/node_modules/@tauri-apps/cli-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @tauri-apps/cli-linux-arm-gnueabihf@1.2.2: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for token-types@5.0.1: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: token-types@5.0.1
npm WARN notsup Unsupported engine for strtok3@7.0.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: strtok3@7.0.0
npm WARN notsup Unsupported engine for peek-readable@5.0.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: peek-readable@5.0.0
npm WARN notsup Unsupported engine for strip-ansi@7.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: strip-ansi@7.0.1
npm WARN notsup Unsupported engine for is-interactive@2.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: is-interactive@2.0.0
npm WARN notsup Unsupported engine for is-unicode-supported@1.3.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: is-unicode-supported@1.3.0
npm WARN notsup Unsupported engine for log-symbols@5.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: log-symbols@5.1.0
npm WARN notsup Unsupported engine for cli-cursor@4.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: cli-cursor@4.0.0
npm WARN notsup Unsupported engine for restore-cursor@4.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: restore-cursor@4.0.0
npm WARN notsup Unsupported engine for ansi-regex@6.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: ansi-regex@6.0.1
npm WARN notsup Unsupported engine for has-yarn@3.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: has-yarn@3.0.0
npm WARN notsup Unsupported engine for is-npm@6.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: is-npm@6.0.0
npm WARN notsup Unsupported engine for is-yarn-global@0.4.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: is-yarn-global@0.4.1
npm WARN notsup Unsupported engine for latest-version@7.0.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: latest-version@7.0.0
npm WARN notsup Unsupported engine for pupa@3.1.0: wanted: {"node":">=12.20"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: pupa@3.1.0
npm WARN notsup Unsupported engine for boxen@7.0.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: boxen@7.0.0
npm WARN notsup Unsupported engine for configstore@6.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: configstore@6.0.0
npm WARN notsup Unsupported engine for semver-diff@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: semver-diff@4.0.0
npm WARN notsup Unsupported engine for xdg-basedir@5.1.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: xdg-basedir@5.1.0
npm WARN notsup Unsupported engine for string-width@5.1.2: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: string-width@5.1.2
npm WARN notsup Unsupported engine for camelcase@7.0.1: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: camelcase@7.0.1
npm WARN notsup Unsupported engine for widest-line@4.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: widest-line@4.0.1
npm WARN notsup Unsupported engine for type-fest@2.19.0: wanted: {"node":">=12.20"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: type-fest@2.19.0
npm WARN notsup Unsupported engine for wrap-ansi@8.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: wrap-ansi@8.0.1
npm WARN notsup Unsupported engine for ansi-styles@6.2.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: ansi-styles@6.2.1
npm WARN notsup Unsupported engine for unique-string@3.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: unique-string@3.0.0
npm WARN notsup Unsupported engine for crypto-random-string@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: crypto-random-string@4.0.0
npm WARN notsup Unsupported engine for package-json@8.1.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: package-json@8.1.0
npm WARN notsup Unsupported engine for registry-url@6.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: registry-url@6.0.1
npm WARN notsup Unsupported engine for registry-auth-token@5.0.1: wanted: {"node":">=14"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: registry-auth-token@5.0.1
npm WARN notsup Unsupported engine for got@12.5.3: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: got@12.5.3
npm WARN notsup Unsupported engine for lowercase-keys@3.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: lowercase-keys@3.0.0
npm WARN notsup Unsupported engine for p-cancelable@3.0.0: wanted: {"node":">=12.20"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: p-cancelable@3.0.0
npm WARN notsup Unsupported engine for @szmarczak/http-timer@5.0.1: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: @szmarczak/http-timer@5.0.1
npm WARN notsup Unsupported engine for cacheable-lookup@7.0.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: cacheable-lookup@7.0.0
npm WARN notsup Unsupported engine for form-data-encoder@2.1.4: wanted: {"node":">= 14.17"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: form-data-encoder@2.1.4
npm WARN notsup Unsupported engine for cacheable-request@10.2.3: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: cacheable-request@10.2.3
npm WARN notsup Unsupported engine for @sindresorhus/is@5.3.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: @sindresorhus/is@5.3.0
npm WARN notsup Unsupported engine for responselike@3.0.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: responselike@3.0.0
npm WARN notsup Unsupported engine for mimic-response@4.0.0: wanted: {"node":"^12.20.0 || ^14.13.1 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: mimic-response@4.0.0
npm WARN notsup Unsupported engine for normalize-url@8.0.0: wanted: {"node":">=14.16"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: normalize-url@8.0.0
npm WARN notsup Unsupported engine for @pnpm/npm-conf@1.0.5: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: @pnpm/npm-conf@1.0.5
npm WARN notsup Unsupported engine for @pnpm/network.ca-file@1.0.2: wanted: {"node":">=12.22.0"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: @pnpm/network.ca-file@1.0.2
npm WARN notsup Unsupported engine for escape-goat@4.0.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: escape-goat@4.0.0

+ pake-cli@0.1.3
updated 1 package in 3.177s
```
但是要執行就會發生錯誤
```
cch@c034:~/git/Pake$ pake --help
/home/cch/.nvm/versions/node/v10.19.0/lib/node_modules/pake-cli/cli.js:2
import './dist/cli.js';
       ^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
cch@c034:~/git/Pake$ 
```
OS: ubuntu 22.04 x64
node version: v10.19.0
npm version: 6.13.4
rust: rustc 1.63.0 (4b91a6ea7 2022-08-08)

**Comment by changchichung** [comment]
自己更新一下

npm/node 版本太舊了，不過packages.json 裡面也沒寫要用哪一個版本
反正我是去抓最新版的更新之後，就沒問題了
