### ISSUE TITLE
打包的时候报错  Error failed to get project out directory: failed to get cargo metadata: No such file or directory

### ISSUE THREAD

**Issue by yuanmouren1hao** [tw93/Pake#326]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

[root@VM-0-3-centos:/root]#pake -V
1.2.7

### System version

centos 7.6

### Node.js version

[root@VM-0-3-centos:/root]#node -v
v16.18.1

[root@VM-0-3-centos:/root]#rustc -V
rustc 1.67.1 (d5a82bbd2 2023-02-07) (Red Hat 1.67.1-1.el7)

### Minimal reproduce step

[root@VM-0-3-centos:/root]#pake https://weekly.tw93.fun --name weekly 
To build the Linux app, you need to install Rust and Linux package
See more in https://tauri.app/v1/guides/getting-started/prerequisites#installing

You haven't provided an app icon, so the default icon will be used. To assign a custom icon, please use the --icon option.

up to date, audited 234 packages in 574ms

77 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> pake-cli@1.2.7 build
> npm run tauri build --release

> pake-cli@1.2.7 tauri
> tauri build

       Error failed to get project out directory: failed to get cargo metadata: No such file or directory (os error 2)
file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1804
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1804:24
    at /usr/local/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:410:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

按照指引打包，出现上述错误，参考160没办法解决

### What did you expect to see?

。

### What did you see instead?

。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by CREATE-AI** [comment]
mac 也出相同问题

**Comment by tw93** [comment]
Pake 版本看了下也比较老了，可以更新到最新
npm i pake-cli@latest -g

**Comment by artiely** [comment]
mac m1同样的问题

**Comment by artiely** [comment]
`✺ Building app...
       Error failed to get cargo metadata: No such file or directory (os error 2)
file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:369
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:369:24
    at /usr/local/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)`

**Comment by artiely** [comment]
```
✺ Building app...
       Error failed to get cargo metadata: No such file or directory (os error 2)
file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:369
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:369:24
    at /usr/local/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by Maybe-U** [comment]
reload shell sloved

**Comment by Lgowen** [comment]
> ```
> ✺ Building app...
>        Error failed to get cargo metadata: No such file or directory (os error 2)
> file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:369
>                 reject(new Error(`${code}`));
>                        ^
> 
> Error: 1
>     at file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:369:24
>     at /usr/local/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
>     at ChildProcess.exithandler (node:child_process:427:5)
>     at ChildProcess.emit (node:events:514:28)
>     at maybeClose (node:internal/child_process:1091:16)
>     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
> ```

同mac m1一样的问题 有解决方案吗

**Comment by lppjiau** [comment]
> To get started you may need to restart your current shell

thank you! useful to me!
