### ISSUE TITLE
[Bug] Error `tauri.conf.json` error on `tauri > bundle > targets`: ["all"] is not valid under any of the given schemas

### ISSUE THREAD

**Issue by SShnoodles** [tw93/Pake#361]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

1.3.0

### System version

Manjaro Linux x86_64 KDE

### Node.js version

18.14.2

### Minimal reproduce step

pake {url} --name desktop-client --transparent

### What did you expect to see?

build `deb` success

### What did you see instead?

Error logs
```
npm verb reify failed optional dependency /home/shun/node/lib/node_modules/pake-cli/node_modules/fsevents
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 33526ms

up to date, audited 237 packages in 34s

78 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm verb exit 0
npm info ok

> pake-cli@1.3.0 build
> npm run tauri build --release


> pake-cli@1.3.0 tauri
> tauri build

       Error `tauri.conf.json` error on `tauri > bundle > targets`: ["all"] is not valid under any of the given schemas
file:///home/shun/node/lib/node_modules/pake-cli/dist/cli.js:1828
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///home/shun/node/lib/node_modules/pake-cli/dist/cli.js:1828:24
    at /home/shun/node/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

Node.js v18.14.2
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by SShnoodles** [comment]
#360 https://github.com/tw93/Pake/issues/113
