### ISSUE TITLE
[Bug] $HOME/Library/Application: No such file or directory

### ISSUE THREAD

**Issue by zxh326** [tw93/Pake#487]
### Search before asking

- [ ] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

➜  pake --version
2.1.9

### System version

macOS Ventura 13.4.1

### Node.js version

➜  node -v
v18.16.1

> fnm install

### Minimal reproduce step

```sh
➜  pake https://v2ex.com
✔ Enter your application name … V2ex
✼ No icon given, default in use. For a custom icon, use --icon option.
✸ Installing package...

up to date in 649ms

68 packages are looking for funding
✔ Package installed!
✼ The first packaging may be slow, please be patient and wait, it will be faster afterwards.
✦ Building app...
/bin/sh: line 0: cd: /Users/zzde/Library/Application: No such file or directory
file:///Users/zzde/Library/Application%20Support/fnm/node-versions/v18.16.1/installation/lib/node_modules/pake-cli/dist/cli.js:369
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///Users/zzde/Library/Application%20Support/fnm/node-versions/v18.16.1/installation/lib/node_modules/pake-cli/dist/cli.js:369:24
    at /Users/zzde/Library/Application Support/fnm/node-versions/v18.16.1/installation/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)

Node.js v18.16.1
```

### What did you expect to see?

pake success ? ( may be

### What did you see instead?

/bin/sh: line 0: cd: /Users/zzde/Library/Application: No such file or directory
file:///Users/zzde/Library/Application%20Support/fnm/node-versions/v18.16.1/installation/lib/node_modules/pake-cli/dist/cli.js:369
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///Users/zzde/Library/Application%20Support/fnm/node-versions/v18.16.1/installation/lib/node_modules/pake-cli/dist/cli.js:369:24
    at /Users/zzde/Library/Application Support/fnm/node-versions/v18.16.1/installation/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)

### Anything else?

找到一个类似的 issue？

https://github.com/tw93/Pake/issues/314

也是因为 fnm？但好像 1.2.6 已经修了？但我用的是 2.X

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zxh326** [comment]
可以了，感谢
