### ISSUE TITLE
[Bug] Cannot find module '@tauri-apps/cli-darwin-arm64'

### ISSUE THREAD

**Issue by guihouchang** [tw93/Pake#491]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

pake -v  
2.1.12

### System version

MacBook Pro (13-inch, M1, 2020)

### Node.js version

 node -v
v20.4.0

### Minimal reproduce step

pake https://baidu.com --name baidu  --transparent

### What did you expect to see?

build success

### What did you see instead?

tauri build
✸ Building app...
/opt/homebrew/lib/node_modules/pake-cli/node_modules/@tauri-apps/cli/index.js:250
    throw loadError
    ^

Error: Cannot find module '@tauri-apps/cli-darwin-arm64'
Require stack:
- /opt/homebrew/lib/node_modules/pake-cli/node_modules/@tauri-apps/cli/index.js
- /opt/homebrew/lib/node_modules/pake-cli/node_modules/@tauri-apps/cli/main.js
- /opt/homebrew/lib/node_modules/pake-cli/node_modules/@tauri-apps/cli/tauri.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/pake-cli/node_modules/@tauri-apps/cli/index.js:141:29)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/homebrew/lib/node_modules/pake-cli/node_modules/@tauri-apps/cli/index.js',
    '/opt/homebrew/lib/node_modules/pake-cli/node_modules/@tauri-apps/cli/main.js',
    '/opt/homebrew/lib/node_modules/pake-cli/node_modules/@tauri-apps/cli/tauri.js'
  ]
}

Node.js v20.4.0
file:///opt/homebrew/lib/node_modules/pake-cli/dist/cli.js:369
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///opt/homebrew/lib/node_modules/pake-cli/dist/cli.js:369:24
    at /opt/homebrew/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:512:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:512:28)
    at Pipe.<anonymous> (node:net:334:12)

Node.js v20.4.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
辛苦试试 先uninstall，然后重新装下pake，可以试试node18

**Comment by tw93** [comment]
打包错误 合并到这个 https://github.com/tw93/Pake/issues/497
