### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by for-the-zero** [tw93/Pake#518]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

newest

### System version

win10 1909

### Node.js version

v16.15.0

### Minimal reproduce step

```
PS C:\Users\hao> pake https://bing.vcanbb.top/web/#/ --icon https://s10.aconvert.com/convert/p3r68-cdx67/apjnc-wg0yv-001.ico
```
注：icon链接是转换网站的，一段时间后会失效

### What did you expect to see?

……

### What did you see instead?

```
PS C:\Users\hao> pake https://bing.vcanbb.top/web/#/ --icon https://s10.aconvert.com/convert/p3r68-cdx67/apjnc-wg0yv-001.ico
√ Enter your application name ... NewBing
✔ Icon downloaded successfully!
✦ Installing package...
✸ Installing package...

up to date in 6s

68 packages are looking for funding
✔ Package installed!

> pake-cli@2.1.12 build
> npm run tauri build --release


> pake-cli@2.1.12 tauri
> tauri build

   Compiling app v0.1.0 (C:\Users\hao\AppData\Roaming\npm\node_modules\pake-cli\src-tauri)
error: failed to run custom build command for `app v0.1.0 (C:\Users\hao\AppData\Roaming\npm\node_modules\pake-cli\src-tauri)`

Caused by:
  process didn't exit successfully: `C:\Users\hao\AppData\Roaming\npm\node_modules\pake-cli\src-tauri\target\release\build\app-7e917885c7325998\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rerun-if-changed=png\newbing_256.ico
  package.metadata does not exist

  --- stderr
  thread 'main' panicked at 'Are you sure you have RC.EXE in your $PATH?: Error { kind: NotFound, message: "program not found" }', C:\Users\hao\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\embed-resource-2.1.1\src\windows_msvc.rs:37:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       Error failed to build app: failed to build app
file:///C:/Users/hao/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:369
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///C:/Users/hao/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:369:24
    at C:\Users\hao\AppData\Roaming\npm\node_modules\pake-cli\node_modules\shelljs\src\exec.js:145:9
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
辛苦参考这个配置一下，window使用pake稍微麻烦一点  https://tauri.app/v1/guides/getting-started/prerequisites/
