### ISSUE TITLE
Mac 编译报错

### ISSUE THREAD

**Issue by teojs** [tw93/Pake#524]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.2.1

### System version

macOs Ventura 13.3

### Node.js version

v16.16.0

### Minimal reproduce step

pake https://claude.ai/ --name ClaudeAI --icon ./icon/ClaudeAI.icns   

### What did you expect to see?

...

### What did you see instead?

```bash
(base) teo@Friday Downloads % pake https://claude.ai/ --name ClaudeAI --icon ./icon/ClaudeAI.icns     
✦ Installing package...
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more informatio✺ Installing package...
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

up to date in 641ms

68 packages are looking for funding
✔ Package installed!
✼ The first packaging may be slow, please be patient and wait, it will be faster afterwards.
✶ Building app...

> pake-cli@2.2.1 build
> npm run tauri build --release
✵ Building app...

> pake-cli@2.2.1 tauri
> tauri
✵ Building app...
error: failed to get `serde` as a dependency of package `app v0.1.0 (/Users/teo/.nvm/versions/node/v16.16.0/lib/node_modules/pake-cli/src-tauri)`

Caused by:
  failed to load source for dependency `serde`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  usage of sparse registries requires `-Z sparse-registry`
       Error failed to build app: failed to build app
file:///Users/teo/.nvm/versions/node/v16.16.0/lib/node_modules/pake-cli/dist/cli.js:369
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///Users/teo/.nvm/versions/node/v16.16.0/lib/node_modules/pake-cli/dist/cli.js:369:24
    at /Users/teo/.nvm/versions/node/v16.16.0/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by teojs** [comment]
尝试更新pake之后解决了
```bash
 npm i pake-cli@latest -g
```
