### ISSUE TITLE
Windows 编译失败

### ISSUE THREAD

**Issue by DrayChou** [tw93/Pake#56]
与这个类似： https://github.com/tauri-apps/tauri/issues/3941 问题是 Windwos 下 run 的时候会报 icon 文件找不到。试过跳转路径更换目录名等方式，还是一直失败。

```
npm run devwin
Debugger attached.

> devwin
> set TAURI_SKIP_DEVSERVER_CHECK=true && set RUST_BACKTRACE=full && npm run tauri dev

Debugger attached.

> tauri
> tauri dev

Debugger attached.
        Info Watching D:\git\Pake\src-tauri for changes...
   Compiling app v0.1.0 (D:\git\Pake\src-tauri)
error: failed to run custom build command for `app v0.1.0 (D:\git\Pake\src-tauri)`

Caused by:
  process didn't exit successfully: `D:\git\Pake\src-tauri\target\debug\build\app-fca64041c80f0fe0\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=dev
  package.metadata.winres does not exist

  --- stderr
  thread 'main' panicked at 'error found during tauri-build: Error {
      context: "failed to compile `icons/icon.ico` into a Windows Resource file during tauri-build",
      source: Error {
          kind: NotFound,
          message: "program not found",
      },
  }', D:\bin\scoop\persist\Rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-build-1.0.2\src\lib.rs:172:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src/panicking.rs:142:14
     2: tauri_build::build
               at D:\bin\scoop\persist\Rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-build-1.0.2\src\lib.rs:172:5
     3: build_script_build::main
               at .\build.rs:4:5
     4: core::ops::function::FnOnce::call_once
               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\ops/function.rs:248:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

郁闷的我按照官方教程创建了一个空项目：https://tauri.app/zh/v1/guides/getting-started/setup/html-css-js
结果 run 的时候也报这个类似的错误
```
error: failed to run custom build command for `app v0.1.0 (D:\git\test\tauri\src-tauri)`

Caused by:
  process didn't exit successfully: `D:\git\test\tauri\src-tauri\target\debug\build\app-d1c2d846497cff1d\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-cfg=dev
  package.metadata does not exist
  failed to compile `icons/icon.ico` into a Windows Resource file during tauri-build: program not found
warning: build failed, waiting for other jobs to finish...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

求助！谢谢

**Comment by tw93** [comment]
在你的目录下找到icons/icon.ico ，加入 icon.ico 文件试试

**Comment by DrayChou** [comment]
试过,几个层的目录结构都放过了,还是不行.
![image](https://user-images.githubusercontent.com/760245/200232492-ce5d34d3-8baf-45f2-ba2c-99d9590f3835.png)

尝试指定 icon 文件路径也是不行:
```
use tauri_build::{try_build, Attributes, WindowsAttributes};

fn main() {
  // tauri_build::build()

  if let Err(error) = try_build(
    Attributes::new()
      .windows_attributes(WindowsAttributes::new().window_icon_path("icons/icon.ico")),
  ) {
    panic!("Error: {}", error);
  }
}
```
执行日志输出:
```
> set RUST_BACKTRACE=1 && npm run tauri dev

> pake@ tauri G:\git\Pake
> tauri "dev"

        Info Watching G:\git\Pake\src-tauri for changes...
   Compiling app v0.1.0 (G:\git\Pake\src-tauri)
error: failed to run custom build command for `app v0.1.0 (G:\git\Pake\src-tauri)`

Caused by:
  process didn't exit successfully: `G:\git\Pake\src-tauri\target\debug\build\app-114e755bebe3d5fa\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-cfg=dev
  package.metadata does not exist

  --- stderr
  thread 'main' panicked at 'Error: failed to compile `icons/icon.ico` into a Windows Resource file during tauri-build', build.rs:10:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
npm ERR! code ELIFECYCLE
npm ERR! errno 101
npm ERR! pake@ tauri: `tauri "dev"`
npm ERR! Exit status 101
npm ERR!
npm ERR! Failed at the pake@ tauri script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dream\AppData\Roaming\npm-cache\_logs\2022-11-07T05_30_11_241Z-debug.log
```
报错的日志文件内容:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\bin\\nodejs\\node.exe',
1 verbose cli   'D:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'tauri',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.14
3 info using node@v14.17.4
4 verbose run-script [ 'pretauri', 'tauri', 'posttauri' ]
5 info lifecycle pake@~pretauri: pake@
6 info lifecycle pake@~tauri: pake@
7 verbose lifecycle pake@~tauri: unsafe-perm in lifecycle true
8 verbose lifecycle pake@~tauri: PATH: D:\bin\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;G:\git\Pake\node_modules\.bin;D:\bin\scoop\apps\rustup\current\.cargo\bin;C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.6.0_x64__8wekyb3d8bbwe;D:\bin\Python36\Scripts\;D:\bin\Python36\;D:\bin\Java\jdk-8.0.302.8-hotspot\bin;C:\Python27\;C:\Python27\Scripts;C:\Windows;C:\Windows\system32;C:\Windows\System32\Wbem;C:\Windows\System32\OpenSSH\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Python39\Scripts\;C:\Python39\;C:\Python27\Scripts;C:\Python27\;D:\bin\Python36;D:\bin\Python36\Scripts;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;D:\bin\nodejs\;D:\bin\Lua\5.1;D:\bin\Lua\5.1\clibs;D:\bin\Lua\luarocks;D:\portableapps.com\PortableApps\Scrcpy;D:\bin\apache-maven-3.8.1\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;D:\portableapps.com\PortableApps\easy-service\;d:\Program Files\MiKTeX\miktex\bin\x64\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;d:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\Git XL;C:\Program Files\TortoiseSVN\bin;D:\Program Files\Perforce\;D:\Program Files\Beyond Compare 4\;D:\Program Files\TortoiseGit\bin;D:\bin\groovy-4.0.0\bin\;D:\Program Files\PowerShell\7\;C:\Program Files (x86)\ZeroTier\One\;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files (x86)\ZeroTier\One;D:\bin\scoop\apps\python\current\Scripts;D:\bin\scoop\apps\python\current;d:\Program Files\JetBrains\IntelliJ IDEA 2021.1.3\bin
9 verbose lifecycle pake@~tauri: CWD: G:\git\Pake
10 silly lifecycle pake@~tauri: Args: [ '/d /s /c', 'tauri "dev"' ]
11 silly lifecycle pake@~tauri: Returned: code: 101  signal: null
12 info lifecycle pake@~tauri: Failed to exec tauri script
13 verbose stack Error: pake@ tauri: `tauri "dev"`
13 verbose stack Exit status 101
13 verbose stack     at EventEmitter.<anonymous> (D:\bin\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (D:\bin\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid pake@
15 verbose cwd G:\git\Pake
16 verbose Windows_NT 10.0.19042
17 verbose argv "D:\\bin\\nodejs\\node.exe" "D:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tauri" "dev"
18 verbose node v14.17.4
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 101
22 error pake@ tauri: `tauri "dev"`
22 error Exit status 101
23 error Failed at the pake@ tauri script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 101, true ]

```

**Comment by tw93** [comment]
可以等一天，我们贡献者同学已经在提交代码了，可见 https://github.com/tw93/Pake/pull/60

**Comment by DrayChou** [comment]
2022-11-18 更新到最新重新执行 npm run dev
```
> npm run dev
Debugger attached.

> pake@ dev G:\git\Pake
> npm run tauri dev

Debugger attached.

> pake@ tauri G:\git\Pake
> tauri "dev"

Debugger attached.
        Info Watching G:\git\Pake\src-tauri for changes...
    Blocking waiting for file lock on build directory
   Compiling app v0.1.0 (G:\git\Pake\src-tauri)
error: failed to run custom build command for `app v0.1.0 (G:\git\Pake\src-tauri)`

Caused by:
  process didn't exit successfully: `G:\git\Pake\src-tauri\target\debug\build\app-dc8631af5c33d2dd\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-cfg=dev
  package.metadata does not exist

  --- stderr
  thread 'main' panicked at 'Error: failed to compile `icons/icon.ico` into a Windows Resource file during tauri-build', build.rs:10:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
npm ERR! code ELIFECYCLE
npm ERR! errno 101
npm ERR! pake@ tauri: `tauri "dev"`
npm ERR! Exit status 101
npm ERR!
npm ERR! Failed at the pake@ tauri script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2022-11-18T03_38_53_617Z-debug.log
Waiting for the debugger to disconnect...
npm ERR! code ELIFECYCLE
npm ERR! errno 101
npm ERR! pake@ dev: `npm run tauri dev`
npm ERR! Exit status 101
npm ERR!
npm ERR! Failed at the pake@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2022-11-18T03_38_53_748Z-debug.log
Waiting for the debugger to disconnect...
```

日志文件内容：
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\bin\\nodejs\\node.exe',
1 verbose cli   'D:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.14
3 info using node@v14.17.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle pake@~predev: pake@
6 info lifecycle pake@~dev: pake@
7 verbose lifecycle pake@~dev: unsafe-perm in lifecycle true
8 verbose lifecycle pake@~dev: PATH: XXX
9 verbose lifecycle pake@~dev: CWD: G:\git\Pake
10 silly lifecycle pake@~dev: Args: [ '/d /s /c', 'npm run tauri dev' ]
11 silly lifecycle pake@~dev: Returned: code: 101  signal: null
12 info lifecycle pake@~dev: Failed to exec dev script
13 verbose stack Error: pake@ dev: `npm run tauri dev`
13 verbose stack Exit status 101
13 verbose stack     at EventEmitter.<anonymous> (D:\bin\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (D:\bin\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid pake@
15 verbose cwd G:\git\Pake
16 verbose Windows_NT 10.0.19042
17 verbose argv "D:\\bin\\nodejs\\node.exe" "D:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v14.17.4
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 101
22 error pake@ dev: `npm run tauri dev`
22 error Exit status 101
23 error Failed at the pake@ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 101, true ]
```

**Comment by DrayChou** [comment]
应该跟这个有关：https://github.com/tauri-apps/tauri/issues/2871

但是我尝试重新安装 toolchain 相关之后，是不报 icon 的问题了。
```
rustup target remove x86_64-pc-windows-gnu
rustup target add x86_64-pc-windows-msvc
rustup toolchain install stable-msvc
rustup default stable-msvc
```

但是开始报更奇怪的问题：
```
> npm run dev

> pake@ dev G:\git\Pake
> npm run tauri dev -- --target x86_64-pc-windows-msvc


> pake@ tauri G:\git\Pake
> tauri "dev" "--target" "x86_64-pc-windows-msvc"

        Info Watching G:\git\Pake\src-tauri for changes...
   Compiling proc-macro2 v1.0.47
   Compiling unicode-ident v1.0.5
   Compiling quote v1.0.21
   Compiling syn v1.0.103
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.147
   Compiling serde v1.0.147
   Compiling ppv-lite86 v0.2.17
   Compiling siphasher v0.3.10
   Compiling getrandom v0.1.16
   Compiling windows_x86_64_msvc v0.42.0
   Compiling phf_shared v0.8.0
   Compiling log v0.4.17
   Compiling memchr v2.5.0
   Compiling getrandom v0.2.8
   Compiling lock_api v0.4.9
   Compiling proc-macro-hack v0.5.19
   Compiling rand_core v0.5.1
   Compiling parking_lot_core v0.9.4
   Compiling rand_core v0.6.4
   Compiling rand_chacha v0.2.2
   Compiling rand_pcg v0.2.1
   Compiling rand_chacha v0.3.1
   Compiling phf_shared v0.10.0
   Compiling windows-tokens v0.39.0
   Compiling rand v0.7.3
   Compiling rand v0.8.5
   Compiling windows_x86_64_msvc v0.39.0
   Compiling thiserror v1.0.37
   Compiling serde_json v1.0.87
   Compiling phf_generator v0.8.0
   Compiling phf_generator v0.10.0
   Compiling phf_codegen v0.8.0
   Compiling string_cache_codegen v0.5.2
   Compiling winapi v0.3.9
   Compiling itoa v1.0.4
   Compiling ryu v1.0.11
   Compiling windows-sys v0.42.0
   Compiling ident_case v1.0.1
   Compiling selectors v0.22.0
   Compiling strsim v0.10.0
   Compiling smallvec v1.10.0
   Compiling fnv v1.0.7
   Compiling convert_case v0.4.0
   Compiling byteorder v1.4.3
   Compiling markup5ever v0.10.1
   Compiling scopeguard v1.1.0
   Compiling once_cell v1.16.0
   Compiling new_debug_unreachable v1.0.4
   Compiling aho-corasick v0.7.19
   Compiling parking_lot v0.12.1
   Compiling tinyvec_macros v0.1.0
   Compiling precomputed-hash v0.1.1
   Compiling mac v0.1.1
   Compiling darling_core v0.13.4
   Compiling bitflags v1.3.2
   Compiling regex-syntax v0.6.28
   Compiling futf v0.1.5
   Compiling tinyvec v1.6.0
   Compiling num-traits v0.2.15
   Compiling percent-encoding v2.2.0
   Compiling utf-8 v0.7.6
   Compiling crc32fast v1.3.2
   Compiling dtoa v0.4.8
   Compiling tendril v0.4.3
   Compiling dtoa-short v0.3.3
   Compiling unicode-normalization v0.1.22
   Compiling form_urlencoded v1.1.0
   Compiling num-integer v0.1.45
   Compiling regex v1.7.0
   Compiling lazy_static v1.4.0
   Compiling version_check v0.9.4
   Compiling typenum v1.15.0
   Compiling matches v0.1.9
   Compiling nodrop v0.1.14
   Compiling windows-metadata v0.39.0
   Compiling stable_deref_trait v1.2.0
   Compiling itoa v0.4.8
   Compiling crossbeam-utils v0.8.12
   Compiling unicode-bidi v0.3.8
   Compiling alloc-no-stdlib v2.0.4
   Compiling servo_arc v0.1.1
   Compiling generic-array v0.14.6
   Compiling windows-bindgen v0.39.0
   Compiling alloc-stdlib v0.2.2
   Compiling idna v0.3.0
   Compiling winapi-util v0.1.5
   Compiling fxhash v0.2.1
   Compiling num-rational v0.4.1
   Compiling cty v0.2.2
   Compiling semver v1.0.14
   Compiling thin-slice v0.1.1
   Compiling uuid v0.8.2
   Compiling cfb v0.6.1
   Compiling raw-window-handle v0.5.0
   Compiling same-file v1.0.6
   Compiling brotli-decompressor v2.3.2
   Compiling phf_macros v0.8.0
   Compiling windows-implement v0.39.0
   Compiling cssparser v0.27.2
   Compiling thiserror-impl v1.0.37
   Compiling html5ever v0.25.2
   Compiling cssparser-macros v0.6.0
   Compiling derive_more v0.99.17
   Compiling darling_macro v0.13.4
   Compiling phf_macros v0.10.0
   Compiling ctor v0.1.26
   Compiling windows v0.39.0
   Compiling darling v0.13.4
   Compiling anyhow v1.0.66
   Compiling phf v0.8.0
   Compiling serde_with_macros v1.5.2
   Compiling windows_x86_64_msvc v0.36.1
   Compiling libc v0.2.137
   Compiling bytes v1.2.1
   Compiling phf v0.10.1
   Compiling brotli v3.3.4
   Compiling infer v0.7.0
   Compiling walkdir v2.3.2
   Compiling num-iter v0.1.43
   Compiling glob v0.3.0
   Compiling adler32 v1.2.0
   Compiling color_quant v1.1.0
   Compiling bytemuck v1.12.3
   Compiling heck v0.4.0
   Compiling adler v1.0.2
   Compiling image v0.24.5
   Compiling http v0.2.8
   Compiling crossbeam-channel v0.5.6
   Compiling webview2-com-macros v0.6.0
   Compiling instant v0.1.12
   Compiling unicode-segmentation v1.10.0
   Compiling string_cache v0.8.4
   Compiling url v2.3.1
   Compiling serde_with v1.14.0
   Compiling cc v1.0.76
   Compiling treediff v3.0.2
   Compiling json-patch v0.2.6
   Compiling webview2-com-sys v0.19.0
   Compiling kuchiki v0.8.1
   Compiling tauri-utils v1.2.0
   Compiling heck v0.3.3
   Compiling toml v0.5.9
   Compiling windows-sys v0.36.1
   Compiling tao v0.15.4
   Compiling miniz_oxide v0.5.4
   Compiling deflate v0.7.20
   Compiling inflate v0.3.4
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.3
   Compiling windows_x86_64_msvc v0.37.0
   Compiling digest v0.10.6
   Compiling flate2 v1.0.24
   Compiling png v0.11.0
   Compiling strum_macros v0.22.0
   Compiling miniz_oxide v0.6.2
   Compiling slab v0.4.7
   Compiling futures-task v0.3.25
   Compiling cpufeatures v0.2.5
   Compiling wry v0.22.1
   Compiling futures-core v0.3.25
   Compiling native-tls v0.2.11
   Compiling tauri-runtime v0.12.0
   Compiling sha2 v0.10.6
   Compiling png v0.17.7
   Compiling ico v0.1.0
   Compiling strum v0.22.0
   Compiling schannel v0.1.20
   Compiling cargo_toml v0.13.0
   Compiling winres v0.1.12
   Compiling uuid v1.2.2
   Compiling quick-xml v0.23.1
   Compiling bstr v0.2.17
   Compiling tokio v1.21.2
   Compiling base64 v0.13.1
   Compiling tao v0.14.0
   Compiling futures-util v0.3.25
   Compiling http-range v0.1.5
   Compiling encoding_rs v0.8.31
   Compiling pin-project-lite v0.2.9
   Compiling tauri-runtime-wry v0.12.0
   Compiling rfd v0.10.0
   Compiling dunce v1.0.3
   Compiling tauri-codegen v1.2.0
   Compiling tauri-build v1.2.0
   Compiling globset v0.4.9
   Compiling windows v0.37.0
   Compiling serde_urlencoded v0.7.1
   Compiling tauri v1.2.0
   Compiling serialize-to-javascript-impl v0.1.1
   Compiling futures-macro v0.3.25
   Compiling remove_dir_all v0.5.3
   Compiling dirs-sys-next v0.1.2
   Compiling thread_local v1.1.4
   Compiling filetime v0.2.18
   Compiling num_cpus v1.14.0
   Compiling wry v0.21.1
   Compiling pin-utils v0.1.0
   Compiling fastrand v1.8.0
   Compiling tar v0.4.38
   Compiling serialize-to-javascript v0.1.1
   Compiling tempfile v3.3.0
   Compiling ignore v0.4.18
   Compiling dirs-next v2.0.0
   Compiling attohttpc v0.22.0
   Compiling open v3.0.3
   Compiling os_info v3.5.1
   Compiling serde_repr v0.1.9
   Compiling shared_child v1.0.0
   Compiling os_pipe v1.1.1
   Compiling widestring v1.0.2
   Compiling state v0.5.3
   Compiling webbrowser v0.8.2
   Compiling tauri-macros v1.2.0
   Compiling app v0.1.0 (G:\git\Pake\src-tauri)
   Compiling tauri-winrt-notification v0.1.0
   Compiling notify-rust v4.5.10
   Compiling webview2-com v0.19.1
warning: unused import: `wry::application::platform::windows::WindowBuilderExtWindows`
 --> src\main.rs:5:5
  |
5 | use wry::application::platform::windows::WindowBuilderExtWindows;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `transparent`
  --> src\main.rs:47:9
   |
47 |         transparent,
   |         ^^^^^^^^^^^-
   |         |
   |         help: try removing the field
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `app` (bin "app") generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 3m 51s
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 216, kind: Uncategorized, message: "该版本的 %1 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。" }', src\interface\rust\desktop.rs:46:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

如果直接 npm run tauri build -- --target x86_64-pc-windows-msvc 也是可以生成 exe 的，但是执行的时候会提示
![image](https://user-images.githubusercontent.com/760245/202653545-f7c8e3d9-742e-4c60-b249-80aaf1acce9f.png)

郁闷了，等我再想想

**Comment by DrayChou** [comment]
另外，附录一下
```
scoop install rustup
```
安装的 rustup 默认是 x86_64-pc-windows-gnu 版本
https://github.com/ScoopInstaller/Main/commit/1782799e405cd5dbf45c62b92340615f45fe4480#

**Comment by DrayChou** [comment]
搞定!

彻底清理本地的 Visual Studio 2017 和相关编译环境,重新安装了 Visual Studio 2022 的一套环境,现在能正常 debug 和 build 了.
谢谢

**Comment by cage1618** [comment]
> 搞定!
> 
> 彻底清理本地的 Visual Studio 2017 和相关编译环境,重新安装了 Visual Studio 2022 的一套环境,现在能正常 debug 和 build 了. 谢谢

请问需要清理哪些内容，谢谢
