### ISSUE TITLE
macos 构建失败，node16、18都有试过

### ISSUE THREAD

**Issue by bing127** [tw93/Pake#589]
npm ERR! Cannot read properties of null (reading 'matches')

file:///opt/homebrew/lib/node_modules/pake-cli/dist/cli.js:375
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///opt/homebrew/lib/node_modules/pake-cli/dist/cli.js:375:24
    at /opt/homebrew/lib/node_modules/pake-cli/node_modules/.store/shelljs@0.8.5/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:350:12)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Tlntin** [comment]
可以试试nvm管理nodejs

**Comment by tw93** [comment]
使用Node18
