### ISSUE TITLE
[Bug] 打包时候，error: failed to get `tauri-plugin-window-state` as a dependency of package `app v0.1.0 (C:\Users\hitime\AppData\Roaming\npm\node_modules\pake-cli\src-tauri)

### ISSUE THREAD

**Issue by Joackk** [tw93/Pake#591]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.3.3

### System version

wind10

### Node.js version

20.8.0

### Minimal reproduce step

当我执行打包命令后日志如下，网络正常可以访问谷歌等墙外网站，管理员权限cmd

✼ No icon given, default in use. For a custom icon, use --icon option.
✼ The first use requires installing system dependencies.
✼ See more in https://tauri.app/v1/guides/getting-started/prerequisites.
✺ Installing package...

up to date, audited 226 packages in 1s

69 packages are looking for funding
  run `npm fund` for details

1 low severity vulnerability

Some issues need review, and may require choosing
a different dependency.

√ Package installed!
✼ The first packaging may be slow, please be patient and wait, it will be faster afterwards.
✸ Building app...

> pake-cli@2.3.3 build
> npm run tauri build --release
✶ Building app...

> pake-cli@2.3.3 tauri
> tauri build
✺ Building app...
error: failed to get `tauri-plugin-window-state` as a dependency of package `app v0.1.0 (C:\Users\hitime\AppData\Roaming\npm\node_modules\pake-cli\src-tauri)`

Caused by:
  failed to load source for dependency `tauri-plugin-window-state`

Caused by:
  Unable to update https://github.com/tauri-apps/plugins-workspace?branch=v1#5b814f56

Caused by:
  failed to fetch into: C:\Users\hitime\.cargo\git\db\plugins-workspace-fd0259fcb18f51ad

Caused by:
  could not execute process `git fetch --force --update-head-ok https://github.com/tauri-apps/plugins-workspace +5b814f56e6368fdec46c4ddb04a07e0923ff995a:refs/commit/5b814f56e6368fdec46c4ddb04a07e0923ff995a` (never executed)

Caused by:
  program not found
       Error failed to build app: failed to build app
file:///C:/Users/hitime/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:375
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///C:/Users/hitime/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:375:24
    at C:\Users\hitime\AppData\Roaming\npm\node_modules\pake-cli\node_modules\shelljs\src\exec.js:145:9
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v20.8.0

### What did you expect to see?

我希望她是正确的执行

### What did you see instead?

不知道现在这个问题是什么情况

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Joackk** [comment]
似乎是没安装git的问题，安装了git后正常打包了
