### ISSUE TITLE
希望安装时有代理配置项

### ISSUE THREAD

**Issue by watchingfun** [tw93/Pake#644]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

```
pake-cli@2.3.6 tauri
> tauri build
   Compiling app v0.1.0 (D:\node_package\npm\node_modules\pake-cli\src-tauri)
    Finished release [optimized] target(s) in 28.37s
        Info Verifying wix package
 Downloading https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
       Error failed to bundle project: `https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip: Network Error: Network Error: Error encountered in the status line: unexpected end of file`
file:///D:/node_package/npm/node_modules/pake-cli/dist/cli.js:375
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///D:/node_package/npm/node_modules/pake-cli/dist/cli.js:375:24
    at D:\node_package\npm\node_modules\pake-cli\node_modules\shelljs\src\exec.js:145:9
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhujinwei0527123** [comment]
这个确实有必要

**Comment by tw93** [comment]
建议使用科学上网工具的 增强模式 可以很简单解决这个问题，此外也可以试试这个 https://www.proxifier.com/
