### ISSUE TITLE
[Bug] 命令行--targets appimage报错

### ISSUE THREAD

**Issue by witt-bit** [tw93/Pake#826]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.6.1

### System version

```shell
~ 
❯ screenfetch

 ██████████████████  ████████     witt@witt-pc
 ██████████████████  ████████     OS: Manjaro 24.1.1 Xahea
 ██████████████████  ████████     Kernel: x86_64 Linux 6.10.13-3-MANJARO
 ██████████████████  ████████     Uptime: 31m
 ████████            ████████     Packages: 1381
 ████████  ████████  ████████     Shell: zsh 5.9
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: KDE
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breeze-Dark [GTK2], Breeze [GTK3]
 ████████  ████████  ████████     Icon Theme: Tela-circle-dark
 ████████  ████████  ████████     Disk: 208G / 467G (47%)
 ████████  ████████  ████████     CPU: Intel Core i5-10210U @ 8x 4.2GHz [57.0°C]
 ████████  ████████  ████████     GPU: NVIDIA GeForce MX250
                                  RAM: 6571MiB / 15735MiB
```

### Node.js version

v23.0.0

### Minimal reproduce step

1.执行`npm install -g pake-cli`
2.执行`pake https://qiye.aliyun.com --name aliyun-qiye-mail --hide-title-bar --targets appimage`

### What did you expect to see?

构建出appimage包

### What did you see instead?

```shell
/home🔒 
❯ pake https://qiye.aliyun.com --name aliyun-qiye-mail --hide-title-bar --targets appimage
(node:13122) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✼ No icon given, default in use. For a custom icon, use --icon option.
✼ The first use requires installing system dependencies.
✼ See more in https://tauri.app/v1/guides/getting-started/prerequisites.
✵ Installing package...
(node:13146) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
✺ Installing package...
✺ Installing package...

added 76 packages, and audited 203 packages in 23s

67 packages are looking for funding
  run `npm fund` for details

✔ Package installed!
✼ The first packaging may be slow, please be patient and wait, it will be faster afterwards.
✶ Building app...

> pake-cli@2.6.1 build
> npm run tauri build --release
✵ Building app...

> pake-cli@2.6.1 tauri
> tauri build
✶ Building app...
   Compiling proc-macro2 v1.0.83
   Compiling unicode-ident v1.0.12
   Compiling serde v1.0.202
   Compiling pkg-config v0.3.30
   Compiling hashbrown v0.14.5
   Compiling equivalent v1.0.1
   Compiling smallvec v1.13.2
   Compiling libc v0.2.155
✺ Building app...
✸ Building app...
✹ Building app...
✺ Building app...
✶ Building app...
✸ Building app...
✦ Building app...
   Compiling indexmap v2.2.6
✶ Building app...
   Compiling quote v1.0.36
   Compiling syn v2.0.65
   Compiling cfg-expr v0.15.8
   Compiling version_check v0.9.4
   Compiling ppv-lite86 v0.2.17
   Compiling once_cell v1.19.0
   Compiling memchr v2.7.2
   Compiling winnow v0.5.40
   Compiling futures-core v0.3.30
   Compiling lock_api v0.4.12
   Compiling parking_lot_core v0.9.10
   Compiling getrandom v0.2.15
   Compiling thiserror v1.0.61
   Compiling futures-io v0.3.30
   Compiling getrandom v0.1.16
   Compiling slab v0.4.9
   Compiling cc v1.0.98
   Compiling rand_core v0.6.4
   Compiling rand_core v0.5.1
   Compiling rand_chacha v0.3.1
   Compiling log v0.4.21
   Compiling futures-sink v0.3.30
   Compiling rand v0.8.5
   Compiling bitflags v1.3.2
   Compiling anyhow v1.0.86
   Compiling rand_pcg v0.2.1
   Compiling rand_chacha v0.2.2
   Compiling pin-utils v0.1.0
   Compiling futures-task v0.3.30
   Compiling phf_shared v0.8.0
   Compiling rand v0.7.3
   Compiling phf_shared v0.10.0
   Compiling crossbeam-utils v0.8.20
   Compiling bitflags v2.5.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling semver v1.0.23
   Compiling phf_generator v0.10.0
   Compiling proc-macro-error v1.0.4
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling phf_generator v0.8.0
   Compiling futures-channel v0.3.30
   Compiling scopeguard v1.2.0
   Compiling phf_codegen v0.10.0
   Compiling string_cache_codegen v0.5.2
   Compiling typenum v1.17.0
   Compiling parking_lot v0.12.2
   Compiling heck v0.4.1
   Compiling markup5ever v0.11.0
   Compiling fnv v1.0.7
   Compiling rustix v0.38.34
   Compiling phf_codegen v0.8.0
   Compiling generic-array v0.14.7
   Compiling linux-raw-sys v0.4.14
   Compiling unicode-segmentation v1.11.0
   Compiling selectors v0.22.0
   Compiling rustc_version v0.4.0
   Compiling heck v0.3.3
   Compiling memoffset v0.9.1
   Compiling cfg-expr v0.9.1
   Compiling strsim v0.11.1
   Compiling ident_case v1.0.1
   Compiling version-compare v0.0.11
   Compiling darling_core v0.20.9
   Compiling convert_case v0.4.0
   Compiling parking v2.2.0
   Compiling itoa v1.0.11
   Compiling concurrent-queue v2.5.0
   Compiling phf_shared v0.11.2
   Compiling fastrand v2.1.0
   Compiling phf_generator v0.11.2
   Compiling gio v0.15.12
   Compiling byteorder v1.5.0
   Compiling new_debug_unreachable v1.0.6
   Compiling mac v0.1.1
   Compiling precomputed-hash v0.1.1
   Compiling futf v0.1.5
   Compiling utf-8 v0.7.6
   Compiling vcpkg v0.2.15
   Compiling tinyvec_macros v0.1.1
   Compiling dtoa v1.0.9
   Compiling dtoa-short v0.3.4
   Compiling tinyvec v1.6.0
   Compiling tendril v0.4.3
   Compiling phf_macros v0.8.0
   Compiling serde_derive v1.0.202
   Compiling thiserror-impl v1.0.61
   Compiling futures-macro v0.3.30
   Compiling cssparser v0.27.2
   Compiling cssparser-macros v0.6.1
   Compiling html5ever v0.26.0
   Compiling futures-util v0.3.30
   Compiling derive_more v0.99.17
   Compiling phf_macros v0.11.2
   Compiling darling_macro v0.20.9
   Compiling darling v0.20.9
   Compiling serde_with_macros v3.8.1
   Compiling phf v0.8.0
   Compiling openssl-sys v0.9.102
   Compiling tracing-attributes v0.1.27
   Compiling ctor v0.2.8
   Compiling field-offset v0.3.6
   Compiling phf v0.10.1
   Compiling tracing-core v0.1.32
   Compiling wayland-sys v0.31.1
   Compiling futures-executor v0.3.30
   Compiling libloading v0.8.3
   Compiling indexmap v1.9.3
   Compiling ryu v1.0.18
   Compiling serde_json v1.0.117
   Compiling matches v0.1.10
   Compiling simd-adler32 v0.3.7
   Compiling itoa v0.4.8
   Compiling stable_deref_trait v1.2.0
   Compiling nodrop v0.1.14
   Compiling alloc-no-stdlib v2.0.4
   Compiling alloc-stdlib v0.2.2
   Compiling servo_arc v0.1.1
   Compiling tracing v0.1.40
   Compiling dlib v0.5.2
   Compiling unicode-normalization v0.1.23
   Compiling fxhash v0.2.1
   Compiling wayland-backend v0.3.3
   Compiling uuid v1.8.0
   Compiling gtk v0.15.5
   Compiling cfg_aliases v0.1.1
   Compiling percent-encoding v2.3.1
   Compiling adler v1.0.2
   Compiling unicode-bidi v0.3.15
   Compiling hashbrown v0.12.3
   Compiling thin-slice v0.1.1
   Compiling miniz_oxide v0.7.3
   Compiling form_urlencoded v1.2.1
   Compiling idna v0.5.0
   Compiling cfb v0.7.3
   Compiling nix v0.28.0
   Compiling toml_datetime v0.6.6
   Compiling serde_spanned v0.6.6
   Compiling toml v0.5.11
   Compiling string_cache v0.8.7
   Compiling toml_edit v0.22.13
   Compiling toml_edit v0.19.15
   Compiling bytes v1.6.0
   Compiling toml_edit v0.21.1
   Compiling system-deps v5.0.0
   Compiling http v0.2.12
   Compiling toml v0.8.13
   Compiling proc-macro-crate v1.3.1
   Compiling system-deps v6.2.2
   Compiling soup2-sys v0.2.0
   Compiling javascriptcore-rs-sys v0.4.0
   Compiling brotli-decompressor v2.5.1
   Compiling tokio-macros v2.2.0
   Compiling event-listener v5.3.0
   Compiling event-listener v4.0.3
   Compiling glib-macros v0.15.13
   Compiling gtk3-macros v0.15.6
   Compiling glib-sys v0.15.10
   Compiling gobject-sys v0.15.10
   Compiling gdk-sys v0.15.1
   Compiling gio-sys v0.15.10
   Compiling atk-sys v0.15.1
   Compiling pango-sys v0.15.10
   Compiling gdk-pixbuf-sys v0.15.10
   Compiling cairo-sys-rs v0.15.1
   Compiling gtk-sys v0.15.3
   Compiling quick-xml v0.31.0
   Compiling mio v0.8.11
   Compiling signal-hook-registry v1.4.2
   Compiling num_cpus v1.16.0
   Compiling socket2 v0.5.7
   Compiling crc32fast v1.4.2
   Compiling same-file v1.0.6
   Compiling scoped-tls v1.0.1
   Compiling downcast-rs v1.2.1
   Compiling glib v0.15.12
   Compiling walkdir v2.5.0
   Compiling tokio v1.37.0
   Compiling flate2 v1.0.30
   Compiling wayland-scanner v0.31.1
   Compiling webkit2gtk-sys v0.18.0
   Compiling event-listener-strategy v0.5.2
   Compiling event-listener-strategy v0.4.0
   Compiling brotli v3.5.0
   Compiling kuchikiki v0.8.2
   Compiling proc-macro-crate v3.1.0
   Compiling json-patch v1.4.0
   Compiling infer v0.13.0
   Compiling serde_with v3.8.1
   Compiling url v2.5.0
   Compiling fdeflate v0.3.4
   Compiling phf v0.11.2
   Compiling futures-lite v2.3.0
   Compiling zvariant_utils v2.0.0
   Compiling x11 v2.21.0
   Compiling glob v0.3.1
   Compiling openssl v0.10.64
   Compiling foreign-types-shared v0.1.1
   Compiling dunce v1.0.4
   Compiling foreign-types v0.3.2
   Compiling pango v0.15.10
   Compiling cairo-rs v0.15.12
   Compiling atk v0.15.1
   Compiling tauri-utils v1.5.4
   Compiling png v0.17.13
   Compiling wayland-client v0.31.2
   Compiling async-lock v3.3.0
   Compiling gdkx11-sys v0.15.1
   Compiling enumflags2_derive v0.7.9
   Compiling openssl-macros v0.1.1
   Compiling x11-dl v2.21.0
   Compiling libloading v0.7.4
   Compiling num-traits v0.2.19
   Compiling raw-window-handle v0.5.2
   Compiling minimal-lexical v0.2.1
   Compiling async-task v4.7.1
   Compiling native-tls v0.2.11
   Compiling httparse v1.8.0
   Compiling fixedbitset v0.4.2
   Compiling atomic-waker v1.1.2
   Compiling piper v0.2.2
   Compiling petgraph v0.6.5
   Compiling nom v7.1.3
   Compiling enumflags2 v0.7.9
   Compiling gdk-pixbuf v0.15.11
   Compiling libappindicator-sys v0.7.3
   Compiling wayland-protocols v0.31.2
   Compiling gdk v0.15.4
   Compiling zvariant_derive v4.1.1
   Compiling tokio-util v0.7.11
   Compiling async-channel v2.3.1
   Compiling block-buffer v0.10.4
   Compiling crypto-common v0.1.6
   Compiling aho-corasick v1.1.3
   Compiling tao v0.16.9
   Compiling dirs-sys-next v0.1.2
   Compiling lazy_static v1.4.0
   Compiling home v0.5.9
   Compiling regex-syntax v0.8.3
   Compiling try-lock v0.2.5
   Compiling openssl-probe v0.1.5
   Compiling static_assertions v1.1.0
   Compiling endi v1.1.0
   Compiling zvariant v4.1.1
   Compiling regex-automata v0.4.6
   Compiling want v0.3.1
   Compiling tree_magic_mini v3.1.4
   Compiling dirs-next v2.0.0
   Compiling digest v0.10.7
   Compiling h2 v0.3.26
   Compiling blocking v1.6.0
   Compiling wayland-protocols-wlr v0.2.0
   Compiling soup2 v0.2.1
   Compiling javascriptcore-rs v0.16.0
   Compiling gdkwayland-sys v0.15.3
   Compiling http-body v0.4.6
   Compiling polling v3.7.0
   Compiling tempfile v3.10.1
   Compiling derive-new v0.6.0
   Compiling crossbeam-channel v0.5.13
   Compiling os_pipe v1.1.5
   Compiling instant v0.1.13
   Compiling memoffset v0.7.1
   Compiling x11rb-protocol v0.13.1
   Compiling cpufeatures v0.2.12
   Compiling tower-service v0.3.2
   Compiling bytemuck v1.16.0
   Compiling httpdate v1.0.3
   Compiling tauri-runtime v0.14.3
   Compiling wry v0.24.10
   Compiling hyper v0.14.28
   Compiling image v0.25.1
   Compiling sha2 v0.10.8
   Compiling sha1 v0.10.6
   Compiling wl-clipboard-rs v0.8.1
   Compiling libappindicator v0.7.1
   Compiling x11rb v0.13.1
   Compiling webkit2gtk v0.18.2
   Compiling async-io v2.3.2
   Compiling async-fs v2.1.2
   Compiling ico v0.3.0
   Compiling regex v1.10.4
   Compiling tokio-native-tls v0.3.1
   Compiling zbus_names v3.0.0
   Compiling async-executor v1.11.0
   Compiling zbus_macros v4.2.2
   Compiling async-broadcast v0.7.0
   Compiling toml v0.7.8
   Compiling serde_repr v0.1.19
   Compiling async-trait v0.1.80
   Compiling crossbeam-epoch v0.9.18
   Compiling bstr v1.9.1
   Compiling ordered-stream v0.2.0
   Compiling xdg-home v1.1.0
   Compiling tauri-runtime-wry v0.14.7
   Compiling rfd v0.10.0
   Compiling http-range v0.1.5
   Compiling hex v0.4.3
   Compiling base64 v0.21.7
   Compiling tauri-codegen v1.4.3
   Compiling rustls-pemfile v1.0.4
   Compiling globset v0.4.14
   Compiling crossbeam-deque v0.8.5
   Compiling hyper-tls v0.5.0
   Compiling zbus v4.2.2
   Compiling arboard v3.4.0
   Compiling embed-resource v2.4.2
   Compiling serde_urlencoded v0.7.1
   Compiling xattr v1.3.1
   Compiling serialize-to-javascript-impl v0.1.1
   Compiling tauri v1.6.6
   Compiling filetime v0.2.23
   Compiling encoding_rs v0.8.34
   Compiling sync_wrapper v0.1.2
   Compiling mime v0.3.17
   Compiling pathdiff v0.2.1
   Compiling ipnet v2.9.0
   Compiling open v3.2.0
   Compiling notify-rust v4.11.0
   Compiling reqwest v0.11.27
   Compiling tar v0.4.40
   Compiling serialize-to-javascript v0.1.1
   Compiling tauri-winres v0.1.1
   Compiling tauri-macros v1.4.4
   Compiling nix v0.26.4
   Compiling ignore v0.4.22
   Compiling cargo_toml v0.15.3
   Compiling os_info v3.8.2
   Compiling shared_child v1.0.0
   Compiling sys-locale v0.2.4
   Compiling state v0.5.3
   Compiling tauri-build v1.5.2
   Compiling bincode v1.3.3
   Compiling app v0.1.0 (/home/witt/.nvm/versions/node/v23.0.0/lib/node_modules/pake-cli/src-tauri)
   Compiling tauri-plugin-oauth v0.0.0-alpha.0 (https://github.com/FabianLars/tauri-plugin-oauth?branch=main#50dadbf4)
   Compiling tauri-plugin-window-state v0.1.1 (https://github.com/tauri-apps/plugins-workspace?branch=v1#5e3900e6)
    Finished `release` profile [optimized] target(s) in 3m 52s
        Warn Signing, by default, is only supported on Windows hosts, but you can specify a custom signing command in `bundler > windows > sign_command`, for now, skipping signing the installer...
    Bundling aliyun-qiye-mail_1.0.0_amd64.AppImage (/home/witt/.nvm/versions/node/v23.0.0/lib/node_modules/pake-cli/src-tauri/target/release/bundle/appimage/aliyun-qiye-mail_1.0.0_amd64.AppImage)
       Error failed to bundle project: error running appimage.sh
file:///home/witt/.nvm/versions/node/v23.0.0/lib/node_modules/pake-cli/dist/cli.js:374
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///home/witt/.nvm/versions/node/v23.0.0/lib/node_modules/pake-cli/dist/cli.js:374:24
    at /home/witt/.nvm/versions/node/v23.0.0/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:421:5)
    at ChildProcess.emit (node:events:507:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v23.0.0
```

### Anything else?

node是使用nvm安装的

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by diego-rapoport** [comment]
I'm having the same issue.

**Comment by tw93** [comment]
Finally fixed it, it was caused by the underlying version update, please update pake-cli to the latest version 3.1.1

**Comment by diego-rapoport** [comment]
> Finally fixed it, it was caused by the underlying version update, please update pake-cli to the latest version 3.1.1 @diego-rapoport @witt-bit

```
failed to bundle project: `failed to run linuxdeploy`
    Error failed to bundle project: `failed to run linuxdeploy`
file:///home/dinhego/.nvm/versions/node/v23.5.0/lib/node_modules/pake-cli/dist/cli.js:322
                reject(new Error(`Error occurred while executing command "${command}". Exit code: ${code}`));
                       ^

Error: Error occurred while executing command "cd "/home/dinhego/.nvm/versions/node/v23.5.0/lib/node_modules/pake-cli" && npm run build". Exit code: 1
    at file:///home/dinhego/.nvm/versions/node/v23.5.0/lib/node_modules/pake-cli/dist/cli.js:322:24
    at /home/dinhego/.nvm/versions/node/v23.5.0/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:421:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v23.5.0
```

Tried node version 22.6.0 as well and got the same problem. `pake -v` gets 3.1.1

**Comment by Faccococo** [comment]
> > Finally fixed it, it was caused by the underlying version update, please update pake-cli to the latest version 3.1.1 最后修复了，问题是由于底层版本更新引起的，请将 pake-cli 更新到最新版本 3.1.1。@diego-rapoport @witt-bit
> 
> ```
> failed to bundle project: `failed to run linuxdeploy`
>     Error failed to bundle project: `failed to run linuxdeploy`
> file:///home/dinhego/.nvm/versions/node/v23.5.0/lib/node_modules/pake-cli/dist/cli.js:322
>                 reject(new Error(`Error occurred while executing command "${command}". Exit code: ${code}`));
>                        ^
> 
> Error: Error occurred while executing command "cd "/home/dinhego/.nvm/versions/node/v23.5.0/lib/node_modules/pake-cli" && npm run build". Exit code: 1
>     at file:///home/dinhego/.nvm/versions/node/v23.5.0/lib/node_modules/pake-cli/dist/cli.js:322:24
>     at /home/dinhego/.nvm/versions/node/v23.5.0/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
>     at ChildProcess.exithandler (node:child_process:421:5)
>     at ChildProcess.emit (node:events:513:28)
>     at maybeClose (node:internal/child_process:1101:16)
>     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
> 
> Node.js v23.5.0
> ```
> 
> Tried node version 22.6.0 as well and got the same problem. `pake -v` gets 3.1.1尝试了节点版本 22.6.0，遇到了同样的问题。 `pake -v` 得到 3.1.1。

This is caused by the strip utility
add NO_STRIP=true to linuxdeploy command mannually, and it will be ok

**Comment by diego-rapoport** [comment]
> This is caused by the strip utility add NO_STRIP=true to linuxdeploy command mannually, and it will be ok

That totally worked! Thank you very much @Faccococo

**Comment by jackywu** [comment]
I added `NO_STRIP=true` like the following manner, but it didn't work. how did you get it work, @diego-rapoport ? thanks.

```
sudo env NO_STRIP=true  pake https://chat.deepseek.com --name deepseek --hide-title-bar --icon icons/deepseek.icns --targets appimage

✦ Installing package...

up to date, audited 242 packages in 2s

73 packages are looking for funding
  run `npm fund` for details

✔ Package installed!
✼ Linux icon must be .png and 512x512px., but you give .icns
✼ Icon will remain as default.
pakeConfig {
  windows: [
    {
      url: 'https://chat.deepseek.com',
      url_type: 'web',
      hide_title_bar: true,
      fullscreen: false,
      width: 1200,
      height: 780,
      resizable: true,
      always_on_top: false,
      dark_mode: false,
      activation_shortcut: '',
      disabled_web_shortcuts: false
    }
  ],
  user_agent: {
    macos: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15',
    linux: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
    windows: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'
  },
  system_tray: { macos: false, linux: false, windows: true },
  system_tray_path: 'png/icon_512.png',
  inject: [],
  proxy_url: ''
}
✺ Building app...

> pake-cli@3.1.1 build
> npm run tauri build --release
✸ Building app...
✹ Building app...

> pake-cli@3.1.1 tauri
> tauri build
   Compiling pake v3.1.0 (/usr/lib/node_modules/pake-cli/src-tauri)
    Finished `release` profile [optimized] target(s) in 4m 14s
       Built application at: /usr/lib/node_modules/pake-cli/src-tauri/target/release/pake
    Bundling deepseek_1.0.0_amd64.AppImage (/usr/lib/node_modules/pake-cli/src-tauri/target/release/bundle/appimage/deepseek_1.0.0_amd64.AppImage)
failed to bundle project: `failed to run linuxdeploy`
       Error failed to bundle project: `failed to run linuxdeploy`
file:///usr/lib/node_modules/pake-cli/dist/cli.js:322
                reject(new Error(`Error occurred while executing command "${command}". Exit code: ${code}`));
                       ^

Error: Error occurred while executing command "cd "/usr/lib/node_modules/pake-cli" && npm run build". Exit code: 1
    at file:///usr/lib/node_modules/pake-cli/dist/cli.js:322:24
    at /usr/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:421:5)
    at ChildProcess.emit (node:events:507:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v23.9.0

```

**Comment by dominix** [comment]
I got the same problem.

**Comment by amaramrahul** [comment]
I am also facing the same issue. Running "export NO_STRIP=true" before executing the pake command did not help.

@faccoco @diego-rapoport Any suggestions on how to add NO_STRIP=true to linuxdeploy command manually?
